/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#b1f2be',
        'tertiary-fixed': '#cce5ff',
        'surface-tint': '#95d5a4',
        'on-tertiary-fixed': '#001e31',
        'tertiary-fixed-dim': '#92ccff',
        'primary-container': '#0a4d28',
        'on-secondary': '#003919',
        'secondary-fixed': '#6bfe9c',
        'on-error-container': '#ffdad6',
        'inverse-on-surface': '#2e312d',
        'surface-bright': '#373a36',
        error: '#ffb4ab',
        primary: '#95d5a4',
        'on-primary-fixed': '#00210d',
        'on-primary-container': '#7fbd8e',
        'outline-variant': '#404941',
        'inverse-primary': '#2d6a42',
        'on-background': '#e1e3dd',
        'secondary-fixed-dim': '#4ae183',
        'on-surface-variant': '#c0c9be',
        tertiary: '#92ccff',
        'inverse-surface': '#e1e3dd',
        'surface-variant': '#323632',
        'on-error': '#690005',
        'secondary-container': '#06bb63',
        'surface-container-lowest': '#0c0f0c',
        'surface-container-low': '#191c19',
        'surface-dim': '#111411',
        background: '#111411',
        outline: '#8a9389',
        'on-surface': '#e1e3dd',
        'on-tertiary-fixed-variant': '#004b73',
        secondary: '#4ae183',
        'on-secondary-fixed-variant': '#005228',
        'surface-container': '#1d201d',
        surface: '#111411',
        'on-tertiary': '#003351',
        'on-tertiary-container': '#69b6f2',
        'error-container': '#93000a',
        'surface-container-high': '#272b27',
        'on-primary': '#00391a',
        'on-primary-fixed-variant': '#11512c',
        'on-secondary-fixed': '#00210c',
        'tertiary-container': '#00466c',
        'on-secondary-container': '#00431f',
        'surface-container-highest': '#323632',
        'primary-fixed-dim': '#95d5a4',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        xxl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        gutter: '24px',
      },
      fontFamily: {
        'body-lg': ['Lexend', 'sans-serif'],
        'label-lg': ['Lexend', 'sans-serif'],
        'body-md': ['Lexend', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
        'headline-sm': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-sm': ['20px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
      keyframes: {
        ticker: {
          '0%':   { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'pulse-border': {
          '0%, 100%': { borderColor: 'rgba(74, 225, 131, 0.4)' },
          '50%': { borderColor: 'rgba(74, 225, 131, 1)' },
        },
      },
      animation: {
        ticker: 'ticker 28s linear infinite',
        'pulse-border': 'pulse-border 2s infinite',
      },
    },
  },
  plugins: [],
}
